# Generated by Django 4.2.3 on 2023-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_person_age_person_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_bot',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='language_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
