version: '3.8'
services:
  web:
    image: my-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
    healthcheck:
      test: curl -f http://127.0.0.1:8000/live/healthcheck/ || echo "1"
      interval: 30s
      timeout: 3s
      retries: 12
    networks:
      - your-network
  db:
    image: postgres:15
    env_file: 
      - .env
    ports:
      - "5432:5432"
    networks:
      - your-network

networks:
  your-network: